configpath: 
  logdir1: "D:/golangwork/src/golang-/logcatchsys/logdir1/log.txt"
  logdir2: "D:/golangwork/src/golang-/logcatchsys/logdir2/log.txt"
  logdir4: "D:/golangwork/src/golang-/logcatchsys/logdir4/log.txt"

  
